# /// script
# requires-python = ">=3.13"
# dependencies = ["pillow"]
# ///
"""Turn an image into the C header that Maze's logo is read from.

The device has no PNG decoder, so the image goes in as a raw RGB565 blob with
a 1-bit mask. The layout is documented in
firmware/src/x11shim/include/ximage-loader.h.

Run with: uv run tools/make_logo_blob.py logo-50.gif --name logo_50_png \\
    -o firmware/src/x11shim/include/images/gen/logo-50_png.h
"""

import argparse
import sys
from pathlib import Path

OPAQUE_ALPHA = 128


def rgb565(r: int, g: int, b: int) -> int:
    return (r & 0xF8) << 8 | (g & 0xFC) << 3 | b >> 3


def build_blob(width: int, height: int, rgba: bytes) -> bytes:
    if not (0 < width <= 0xFFFF and 0 < height <= 0xFFFF):
        raise ValueError(f"size {width}x{height} does not fit the blob header")
    if len(rgba) != width * height * 4:
        raise ValueError(f"expected {width * height * 4} RGBA bytes, got {len(rgba)}")

    pixels = bytearray()
    mask = bytearray()
    stride = (width + 7) // 8
    for y in range(height):
        row = bytearray(stride)
        for x in range(width):
            r, g, b, a = rgba[(y * width + x) * 4 :][:4]
            opaque = a >= OPAQUE_ALPHA
            pixels += (rgb565(r, g, b) if opaque else 0).to_bytes(2, "little")
            if opaque:
                row[x // 8] |= 0x80 >> (x % 8)
        mask += row
    header = b"565M" + width.to_bytes(2, "little") + height.to_bytes(2, "little")
    return bytes(header + pixels + mask)


def c_header(name: str, blob: bytes, source: str) -> str:
    guard = f"XSHIM_{name.upper()}_H"
    lines = []
    for i in range(0, len(blob), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i : i + 12]) + ",")
    body = "\n".join(lines)
    return (
        f"/* Generated by tools/make_logo_blob.py from {source}; do not edit.\n"
        " * Despite the name (maze.c asks for a PNG), this is the raw blob\n"
        " * described in ximage-loader.h. */\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n"
        f"static const unsigned char {name}[] = {{\n"
        f"{body}\n"
        "};\n"
        "#endif\n"
    )


def main(argv: list[str]) -> int:
    from PIL import Image

    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("image")
    parser.add_argument("--name", required=True, help="C array name")
    parser.add_argument("-o", "--output", required=True)
    args = parser.parse_args(argv)

    image = Image.open(args.image).convert("RGBA")
    blob = build_blob(image.width, image.height, image.tobytes())
    Path(args.output).write_text(c_header(args.name, blob, Path(args.image).name))
    print(f"{args.output}: {image.width}x{image.height}, {len(blob)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
